#global settings
title: "Hector Borges Portfolio"
description: "Cybersecurity & AI Research Portfolio"
permalink: pretty
url: "https://borgeslebron.github.io"
relative_permalinks: false

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "node_modules"]
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/